services:
  backend:
    build: .
    ports:
      - "5000:5000"
    restart: always
    volumes:
    # MEDIA volume is used to store uploaded files.
    # This mount is needed for persistence.
      - ./docker-data/media:/culivert/backend/static/media
    environment:
      FLASK_SQLALCHEMY_DATABASE_URI: "postgresql://postgres:to_change@db/postgres"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: to_change
      POSTGRES_DB: postgres
    # If you want to initialize the database with some data, put the .sql file in the init-db folder.
    # and uncomment the following line.
    volumes:
      - ./docker-data/init-db:/docker-entrypoint-initdb.d
      # For persistence, uncomment the following line.
      - ./docker-data/data-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"