= Projet PPII1 "CuliVert"

[abstract]
--
Projet visant à créer un site web dédié à la recherche de recettes culinaires, tout en mettant l'accent sur
l'empreinte carbone de chaque recette.  Il vise à promouvoir une alimentation plus durable en permettant
aux utilisateurs de trouver des recettes délicieuses tout en étant conscients de l'impact environnemental
de leurs choix culinaires.
--

[WARNING]
--
Ce dépôt est un dépôt miroir. Il n'est pas mis à jour régulièrement et toutes les modifications doivent
encore toutes être validées sur le projet GitHub déjà existant. Il est inutile d'ouvrir des Issues et
des Merge Requests ici, elles ne seront pas prises en compte.

Ce dépôt a pour unique objectif d'être en accord avec les demandes (tardivement formulées) du projet PPII1.
Il est vivement conseiller de se rendre sur le projet Github qui contient les détails
du projet (Issues, Pull Requests, TODO-list,...).

link:https://github.com/fusetim/PPII1/[Vers le projet GitHub fusetim/PPII1]

Le projet restera privé jusqu'à la fin du projet, il sera ouvert au public à la date de rendue. Cela est dû entre autre
à la nature du projet, qui est un projet scolaire, et qui ne doit donc pas être accessible à tous, et de plus à la
présence de données sensibles (identifiants de connexion à la base de données, etc) qui auraient pu malencontreusement
être rendues publiques. A la date de rendue, tous ces identifiants auront été modifiés. Il est donc inutile de tenter
de se connecter à ces serveurs.
--

== Arborescence du Projet

Le projet se divise en plusieurs composantes principales, chacune ayant un rôle spécifique dans le développement
et le fonctionnement du site.

* link:./backend[]: Cette section regroupe l'ensemble de la logique serveur de l'application. Le backend gère les requêtes, l'accès à la base de données etc.

* link:./frontend[]: La partie client du site est regroupée ici, et elle comprend à la fois l'interface utilisateur et l'interface d'administration.

* link:./scripts[]: Ce répertoire contient divers scripts utiles pour le développement, la maintenance et la gestion du projet.

* link:./specs[]: Ici, vous trouverez les réflexions et documents liés à la conception de l'application, ainsi que les comptes-rendus des réunions. C'est l'endroit où les idées sont formalisées et les décisions prises.

* link:./docs[]: Dans le futur, cette section sera dédiée à la documentation des différents modules de l'application, expliquant comment les installer et les utiliser.

== Contributions

Afin de participer au projet et de voir vos modifications ajoutées à la branche `main` (et donc la
véritable version du site), il vous faudra respecter les règles suivantes :

1. **Commenter** le code
2. **Tester** le code (en écrivant notamment des tests)
3. Écrire des commits suivant la norme link:https://www.conventionalcommits.org/en/v1.0.0/[**Conventional Commit**]
4. Votre branche doit **être à jour** par rapport à `main` (git pull, rebase et autre joyeuseté)
5. Ouvrir une **Pull Request** (ou Merge Request), qui détaille les changements apportés (qui
reprend généralement les commits)