= Backend

Le dossier `backend` de ce projet a pour rôle de gérer toute la logique serveur de l'application. Il
agit comme l'intermédiaire entre l'interface utilisateur (frontend) et la base de données.

== Rôle du Backend

Le backend assure plusieurs fonctions essentielles, notamment :

1. **Gestion des Requêtes HTTP** : Il écoute les requêtes HTTP provenant du frontend, les traite et
retourne les réponses appropriées. Selon la suite des opérations, il sera plus ou moins porté sur
la création d'une API afin de permettre les différentes actions utilisables dans l'application.

2. **Interaction avec la Base de Données** : Le backend communique avec la base de données pour
récupérer et stocker les informations, y compris les recettes et bilans carbone associés. Dans ce
projet, nous utilisons PostgreSQL (SQLite peut etre ?) comme système de gestion de base de données.

3. **Calcul des Bilans Carbone** : Le backend effectue également la partie algorithmique de
l'application, ce qui comprend le calcul pour attribuer un bilan carbone à chaque recette
en fonction de ses ingrédients et de sa préparation, et également les futures fonctionnalités
permettant de générer un menu de semaine en optimisant divers critères.

== Choix Techniques

Le backend est construit en utilisant **Python** :

* le framework **Flask**, un framework de serveur web minimaliste et flexible
* SQLAlchemy, un ORM (Object-Relational Mapping) pour Python qui permet de manipuler des objets
Python comme s'il s'agissait de tables SQL, et par ailleurs permet d'utiliser du SQL pure si
certains membres ne sont pas à l'aise avec l'ORM
* Flask-Login, une extension de Flask qui permet de gérer les sessions utilisateurs, très utile.
* Flask-Migrate, une extension de Flask qui permet de gérer les migrations de la base de données
et permet donc de générer les tables SQL à partir des modèles Python, et vice-versa.

Une tentative a été faire pour structurer le backend en suivant le modèle MVC (Modèle-Vue-Contrôleur),
et de séparer les différentes parties/routes de l'application dans des fichiers/modules différents.
Néanmoins, la structure n'a pas forcément été respectée à la lettre, et il est bien possible que des
améliorations soient à faire. Cela est en partie due au fait que les membres du groupe sont peu
familiers avec le développement web, et que la majorité a dû apprendre sur le tas. Par conséquent,
le chef de projet a fait les meilleurs choix possibles afin que ce projet soit fini dans les temps,
un minimum structuré et fonctionnel.

== Utilisation (Développement)

* Installer Python 3 bien sûr (avec pip)

* Se déplacer dans ce répertoire `cd backend/`

* Installer et activer l'environnement virtuel python
```shell
python3 -m venv .venv/
source .venv/bin/activate
```
* Installer les dépendances
```shell
pip install -r requirements.txt
```

* Finalement lancer Flask
```
python -m flask run
```

[NOTE]
--
Pour mettre à jour la liste de dépendances, utilisez :
```shell
pip freeze > requirements.txt
```
--