"""Adding recipes

Revision ID: 055a2489ea95
Revises: 3a495c78645a
Create Date: 2023-11-22 11:46:04.695150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055a2489ea95'
down_revision = '3a495c78645a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('recipe_uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('author', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
