"""add: display unit in quantity type

Revision ID: 2ecf1812b293
Revises: a22a49737dbd
Create Date: 2023-12-16 15:35:47.504650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecf1812b293'
down_revision = 'a22a49737dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantity_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantity_types', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
