"""add: illustration as user upload

Revision ID: 34846deb5671
Revises: 99a24f2ea178
Create Date: 2023-12-22 16:20:39.665343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34846deb5671'
down_revision = '99a24f2ea178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('illustration_uid', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'user_uploads', ['illustration_uid'], ['upload_uid'], ondelete='SET NULL')
        batch_op.drop_column('illustration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('illustration', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('illustration_uid')

    # ### end Alembic commands ###
