"""add ingredient links and quantity type

Revision ID: 3bc6873ba8d7
Revises: 055a2489ea95
Create Date: 2023-11-23 17:49:54.685491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc6873ba8d7'
down_revision = '055a2489ea95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_links',
    sa.Column('link_uid', sa.UUID(), nullable=False),
    sa.Column('recipe_uid', sa.UUID(), nullable=False),
    sa.Column('ingredient_code', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('quantity_type_uid', sa.UUID(), nullable=False),
    sa.Column('reference_quantity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('link_uid')
    )
    op.create_table('quantity_types',
    sa.Column('quantity_type_uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('localized_key', sa.String(length=100), nullable=True),
    sa.Column('mass_equivalent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('quantity_type_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantity_types')
    op.drop_table('ingredient_links')
    # ### end Alembic commands ###
