"""edit: DELETE ingredientlink ON CASCADE recipe

Revision ID: a22a49737dbd
Revises: f750adc4f46c
Create Date: 2023-12-16 15:03:01.727261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22a49737dbd'
down_revision = 'f750adc4f46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_links', schema=None) as batch_op:
        batch_op.drop_constraint('ingredient_links_recipe_uid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_uid'], ['recipe_uid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ingredient_links_recipe_uid_fkey', 'recipes', ['recipe_uid'], ['recipe_uid'])

    # ### end Alembic commands ###
