"""add normalized_name for search purposes

Revision ID: ab96f866fd19
Revises: 3bc6873ba8d7
Create Date: 2023-11-25 15:30:48.216040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab96f866fd19'
down_revision = '3bc6873ba8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_name', sa.Text(), nullable=True))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_name', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('normalized_name')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('normalized_name')

    # ### end Alembic commands ###
