"""add: user display_name + avatar

Revision ID: f0ab2bfcb41e
Revises: 2451852c5348
Create Date: 2023-12-22 15:02:07.035251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ab2bfcb41e'
down_revision = '2451852c5348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar_uid', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'user_uploads', ['avatar_uid'], ['upload_uid'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('avatar_uid')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
