"""add: recipe tags

Revision ID: f750adc4f46c
Revises: a46a8a5d4741
Create Date: 2023-12-16 15:01:37.716905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f750adc4f46c'
down_revision = 'a46a8a5d4741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_tags',
    sa.Column('recipe_tag_uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('recipe_tag_uid')
    )
    op.create_table('recipe_tag_links',
    sa.Column('recipe_uid', sa.UUID(), nullable=False),
    sa.Column('recipe_tag_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_tag_uid'], ['recipe_tags.recipe_tag_uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_uid'], ['recipes.recipe_uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_uid', 'recipe_tag_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_tag_links')
    op.drop_table('recipe_tags')
    # ### end Alembic commands ###
