= CR Réunion - 18/12/2023

|===
|Motif |Lieu| Date

|Réunion de suivi |TELECOM Nancy, 1.15 |12/12/2023 9h00-9h40
|===


== Participants

* Sacha BANAK
* Timothée BRILLAUD
* Clément ESCUDE-COTINAT
* Guillaume HISLEUR

== Ordre du jour

* Avancements

== Échanges

=== Avancements & Mise au point

* Front des pages accueil et recherche en cours, backend fait, CSS à faire (Sacha).

* Pull request demandée pour la page d'accueil et la recherche dans l'état afin de merge +
la page recette et l'intégrer.

* Page recette faite, terminée et intégrée, merge à effectuer. (Timothée)

* Documentation, des schémas de BDD, et de l'installation. (Timothée)

* Avancement limité sur la page d'accueil et de recherche. (Sacha)

* Avancement limité sur l'API, mais ça devrait aller plus vite, Clément a son chargeur. + 
La responsabilité des routes admin est à discuter, si clémnet a le temps il les fait.

* Avancement limité sur la partie Admin, travail important sur le CSS (Guillaume).

* Discussions sur le fonctionnement de frontend.

* Discussions internes sur le fonctionnement du panel admin.

== Décisions

=== Avancements

* Accords sur les transferts de données du panel admin.

* Début de la partie compte utilisateurs.

== TODO-List

Allez voir sur Github

== Pour la suite

Prochaine réunion : Mardi 2 janvier à 16h, fin prévu avant 17h.

=== Annexes
